# Generated by Django 2.1.5 on 2019-02-01 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imei', models.CharField(max_length=50)),
                ('Plaque', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=10)),
                ('Price', models.IntegerField()),
                ('Id_device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Register.Device')),
                ('Id_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
